import { DatabaseMigration } from "./migration.types";
import { executeSqlStatements } from "./sql-migration.helpers";

const upStatements = [
  `CREATE SCHEMA IF NOT EXISTS profile`,
  `CREATE SCHEMA IF NOT EXISTS media`,
  `CREATE TABLE profile.onboarding (
     user_id uuid PRIMARY KEY REFERENCES public.usuarios(id) ON DELETE CASCADE,
     status varchar(24) NOT NULL DEFAULT 'NOT_STARTED',
     current_step integer NOT NULL DEFAULT 1,
     completed_steps jsonb NOT NULL DEFAULT '[]'::jsonb,
     version integer NOT NULL DEFAULT 1,
     primary_goal varchar(40),
     experience_level varchar(24),
     weekly_frequency smallint,
     training_location varchar(24),
     available_equipment jsonb NOT NULL DEFAULT '[]'::jsonb,
     training_preferences jsonb NOT NULL DEFAULT '[]'::jsonb,
     physical_considerations text,
     weight_unit varchar(4) NOT NULL DEFAULT 'KG',
     height_unit varchar(4) NOT NULL DEFAULT 'CM',
     height_value numeric(7,2),
     consent_health boolean NOT NULL DEFAULT false,
     consent_data boolean NOT NULL DEFAULT false,
     started_at timestamptz,
     completed_at timestamptz,
     created_at timestamptz NOT NULL DEFAULT now(),
     updated_at timestamptz NOT NULL DEFAULT now(),
     CONSTRAINT ck_onboarding_status CHECK (status IN ('NOT_STARTED','IN_PROGRESS','COMPLETED','REQUIRES_UPDATE')),
     CONSTRAINT ck_onboarding_step CHECK (current_step BETWEEN 1 AND 5),
     CONSTRAINT ck_onboarding_goal CHECK (primary_goal IS NULL OR primary_goal IN ('GAIN_MUSCLE','LOSE_FAT','IMPROVE_STRENGTH','IMPROVE_ENDURANCE','MAINTAIN_FITNESS','GENERAL_HEALTH','SPORT_PERFORMANCE')),
     CONSTRAINT ck_onboarding_experience CHECK (experience_level IS NULL OR experience_level IN ('BEGINNER','INTERMEDIATE','ADVANCED')),
     CONSTRAINT ck_onboarding_frequency CHECK (weekly_frequency IS NULL OR weekly_frequency BETWEEN 1 AND 7),
     CONSTRAINT ck_onboarding_location CHECK (training_location IS NULL OR training_location IN ('GYM','HOME','OUTDOORS','MIXED')),
     CONSTRAINT ck_onboarding_units CHECK (weight_unit IN ('KG','LB') AND height_unit IN ('CM','IN')),
     CONSTRAINT ck_onboarding_height CHECK (height_value IS NULL OR height_value > 0),
     CONSTRAINT ck_onboarding_steps_json CHECK (jsonb_typeof(completed_steps) = 'array'),
     CONSTRAINT ck_onboarding_equipment_json CHECK (jsonb_typeof(available_equipment) = 'array'),
     CONSTRAINT ck_onboarding_preferences_json CHECK (jsonb_typeof(training_preferences) = 'array')
   )`,
  `CREATE TABLE profile.body_measurements (
     id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
     user_id uuid NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
     weight numeric(7,2) NOT NULL,
     unit varchar(4) NOT NULL,
     measured_on date NOT NULL,
     source varchar(24) NOT NULL,
     created_by_user_id uuid NOT NULL REFERENCES public.usuarios(id) ON DELETE RESTRICT,
     idempotency_key varchar(120),
     created_at timestamptz NOT NULL DEFAULT now(),
     CONSTRAINT ck_body_measurement_weight CHECK (weight > 0 AND weight <= 1000),
     CONSTRAINT ck_body_measurement_unit CHECK (unit IN ('KG','LB')),
     CONSTRAINT ck_body_measurement_source CHECK (source IN ('ONBOARDING','PROFILE','USER','ADMIN')),
     CONSTRAINT uq_body_measurement_idempotency UNIQUE NULLS NOT DISTINCT (user_id, idempotency_key)
   )`,
  `CREATE INDEX ix_body_measurements_user_date ON profile.body_measurements(user_id, measured_on DESC, created_at DESC)`,
  `ALTER TABLE public.perfiles_antropometricos ALTER COLUMN edad DROP NOT NULL`,
  `CREATE TABLE media.files (
     id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
     public_id uuid NOT NULL DEFAULT uuid_generate_v4() UNIQUE,
     code varchar(120) NOT NULL UNIQUE,
     name varchar(180) NOT NULL,
     file_type varchar(30) NOT NULL,
     mime_type varchar(100) NOT NULL,
     source_type varchar(30) NOT NULL,
     source_name varchar(120) NOT NULL,
     source_url text NOT NULL,
     storage_url text,
     alt_text varchar(300) NOT NULL,
     width integer,
     height integer,
     license varchar(160) NOT NULL,
     attribution varchar(500) NOT NULL,
     status varchar(20) NOT NULL DEFAULT 'ACTIVE',
     created_at timestamptz NOT NULL DEFAULT now(),
     updated_at timestamptz NOT NULL DEFAULT now(),
     CONSTRAINT ck_media_file_type CHECK (file_type IN ('IMAGE','GIF','VIDEO','DOCUMENT')),
     CONSTRAINT ck_media_source_type CHECK (source_type IN ('EXTERNAL','MANAGED')),
     CONSTRAINT ck_media_status CHECK (status IN ('ACTIVE','INACTIVE')),
     CONSTRAINT ck_media_dimensions CHECK ((width IS NULL AND height IS NULL) OR (width > 0 AND height > 0))
   )`,
  `ALTER TABLE membership.plans ADD COLUMN public_id uuid NOT NULL DEFAULT uuid_generate_v4()`,
  `ALTER TABLE membership.plans ADD COLUMN price_amount numeric(12,2)`,
  `ALTER TABLE membership.plans ADD COLUMN currency char(3)`,
  `ALTER TABLE membership.plans ADD COLUMN image_file_id uuid REFERENCES media.files(id) ON DELETE SET NULL`,
  `ALTER TABLE membership.plans ADD COLUMN benefits jsonb NOT NULL DEFAULT '[]'::jsonb`,
  `ALTER TABLE membership.plans ADD COLUMN display_order integer NOT NULL DEFAULT 0`,
  `ALTER TABLE membership.plans ADD COLUMN available_new boolean NOT NULL DEFAULT true`,
  `ALTER TABLE membership.plans ADD COLUMN available_renewal boolean NOT NULL DEFAULT true`,
  `ALTER TABLE membership.plans ADD COLUMN available_extension boolean NOT NULL DEFAULT true`,
  `ALTER TABLE membership.plans ADD CONSTRAINT uq_membership_plan_public_id UNIQUE (public_id)`,
  `ALTER TABLE membership.plans ADD CONSTRAINT ck_membership_plan_price CHECK ((price_amount IS NULL AND currency IS NULL) OR (price_amount >= 0 AND currency ~ '^[A-Z]{3}$'))`,
  `ALTER TABLE membership.plans ADD CONSTRAINT ck_membership_plan_benefits CHECK (jsonb_typeof(benefits) = 'array')`,
  `CREATE TABLE membership.features (
     id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
     code varchar(100) NOT NULL UNIQUE,
     name varchar(180) NOT NULL,
     description text,
     status varchar(20) NOT NULL DEFAULT 'ACTIVE',
     created_at timestamptz NOT NULL DEFAULT now(),
     updated_at timestamptz NOT NULL DEFAULT now(),
     CONSTRAINT ck_membership_feature_status CHECK (status IN ('ACTIVE','INACTIVE'))
   )`,
  `CREATE TABLE membership.plan_features (
     plan_id uuid NOT NULL REFERENCES membership.plans(id) ON DELETE CASCADE,
     feature_id uuid NOT NULL REFERENCES membership.features(id) ON DELETE RESTRICT,
     created_at timestamptz NOT NULL DEFAULT now(),
     PRIMARY KEY (plan_id, feature_id)
   )`,
  `CREATE TABLE membership.entitlements (
     id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
     user_id uuid NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
     feature_id uuid NOT NULL REFERENCES membership.features(id) ON DELETE RESTRICT,
     source_type varchar(24) NOT NULL,
     source_id uuid NOT NULL,
     status varchar(20) NOT NULL DEFAULT 'ACTIVE',
     starts_at timestamptz NOT NULL,
     ends_at timestamptz,
     metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
     created_at timestamptz NOT NULL DEFAULT now(),
     updated_at timestamptz NOT NULL DEFAULT now(),
     CONSTRAINT ck_entitlement_source CHECK (source_type IN ('MEMBERSHIP','PURCHASE','ADMIN_GRANT','PROMOTION','TRIAL')),
     CONSTRAINT ck_entitlement_status CHECK (status IN ('ACTIVE','REVOKED','EXPIRED')),
     CONSTRAINT ck_entitlement_dates CHECK (ends_at IS NULL OR ends_at >= starts_at),
     CONSTRAINT uq_entitlement_source UNIQUE (user_id, feature_id, source_type, source_id)
   )`,
  `CREATE INDEX ix_entitlements_user_active ON membership.entitlements(user_id, status, ends_at)`,
  `CREATE TABLE membership.intents (
     id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
     public_id uuid NOT NULL DEFAULT uuid_generate_v4() UNIQUE,
     user_id uuid NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
     membership_id uuid REFERENCES membership.memberships(id) ON DELETE SET NULL,
     plan_id uuid NOT NULL REFERENCES membership.plans(id) ON DELETE RESTRICT,
     intent_type varchar(20) NOT NULL,
     months integer NOT NULL DEFAULT 1,
     status varchar(24) NOT NULL DEFAULT 'PENDING_PAYMENT',
     channel varchar(20) NOT NULL,
     idempotency_key varchar(120) NOT NULL,
     correlation_id uuid NOT NULL,
     confirmed_at timestamptz,
     created_at timestamptz NOT NULL DEFAULT now(),
     updated_at timestamptz NOT NULL DEFAULT now(),
     CONSTRAINT ck_membership_intent_type CHECK (intent_type IN ('RENEWAL','EXTENSION')),
     CONSTRAINT ck_membership_intent_months CHECK (months BETWEEN 1 AND 24),
     CONSTRAINT ck_membership_intent_status CHECK (status IN ('PENDING_PAYMENT','CONFIRMED','CANCELLED','EXPIRED')),
     CONSTRAINT ck_membership_intent_channel CHECK (channel IN ('WHATSAPP','MANUAL')),
     CONSTRAINT uq_membership_intent_idempotency UNIQUE (user_id, idempotency_key)
   )`,
  `CREATE TABLE membership.extensions (
     id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
     membership_id uuid NOT NULL REFERENCES membership.memberships(id) ON DELETE RESTRICT,
     intent_id uuid NOT NULL REFERENCES membership.intents(id) ON DELETE RESTRICT UNIQUE,
     previous_ends_on date NOT NULL,
     new_ends_on date NOT NULL,
     added_days integer NOT NULL,
     created_by_user_id uuid NOT NULL REFERENCES public.usuarios(id) ON DELETE RESTRICT,
     created_at timestamptz NOT NULL DEFAULT now(),
     CONSTRAINT ck_membership_extension_dates CHECK (new_ends_on > previous_ends_on AND added_days > 0)
   )`,
] as const;

const downStatements = [
  `DROP TABLE IF EXISTS membership.extensions`,
  `DROP TABLE IF EXISTS membership.intents`,
  `DROP TABLE IF EXISTS membership.entitlements`,
  `DROP TABLE IF EXISTS membership.plan_features`,
  `DROP TABLE IF EXISTS membership.features`,
  `ALTER TABLE membership.plans DROP CONSTRAINT IF EXISTS ck_membership_plan_benefits`,
  `ALTER TABLE membership.plans DROP CONSTRAINT IF EXISTS ck_membership_plan_price`,
  `ALTER TABLE membership.plans DROP CONSTRAINT IF EXISTS uq_membership_plan_public_id`,
  `ALTER TABLE membership.plans DROP COLUMN IF EXISTS available_extension`,
  `ALTER TABLE membership.plans DROP COLUMN IF EXISTS available_renewal`,
  `ALTER TABLE membership.plans DROP COLUMN IF EXISTS available_new`,
  `ALTER TABLE membership.plans DROP COLUMN IF EXISTS display_order`,
  `ALTER TABLE membership.plans DROP COLUMN IF EXISTS benefits`,
  `ALTER TABLE membership.plans DROP COLUMN IF EXISTS image_file_id`,
  `ALTER TABLE membership.plans DROP COLUMN IF EXISTS currency`,
  `ALTER TABLE membership.plans DROP COLUMN IF EXISTS price_amount`,
  `ALTER TABLE membership.plans DROP COLUMN IF EXISTS public_id`,
  `DROP TABLE IF EXISTS media.files`,
  `DROP TABLE IF EXISTS profile.body_measurements`,
  `DROP TABLE IF EXISTS profile.onboarding`,
  `DROP SCHEMA IF EXISTS media`,
  `DROP SCHEMA IF EXISTS profile`,
] as const;

export const customerExperienceMigration: DatabaseMigration = {
  id: "202607220002-customer-experience",
  description:
    "Adds persistent onboarding, measurement history, membership commerce, media assets and entitlements.",
  up: (queryInterface, transaction) =>
    executeSqlStatements(queryInterface, transaction, upStatements),
  down: (queryInterface, transaction) =>
    executeSqlStatements(queryInterface, transaction, downStatements),
};
