/**
 * Nombres en español (es-LA, vocabulario de gimnasio) de los ejercicios más
 * usados del catálogo y de todos los que usan las plantillas «Recomendadas por
 * REPP» (10_CORRECCIONES §C3.b). Revisado a mano: NO es traducción automática.
 * Clave = external_id del snapshot; `en` = nombre exacto del snapshot (el seeder
 * comprueba que coincida y falla si no).
 */
export type SpanishExerciseName = { en: string; es: string };

export const EXERCISE_NAMES_ES: Readonly<Record<string, SpanishExerciseName>> = {
  '0003': { en: 'air bike', es: 'Crunch bicicleta' },
  '0009': { en: 'assisted chest dip (kneeling)', es: 'Fondos asistidos en máquina' },
  '0017': { en: 'assisted pull-up', es: 'Dominadas asistidas' },
  '0019': { en: 'assisted triceps dip (kneeling)', es: 'Fondos de tríceps asistidos en máquina' },
  '0025': { en: 'barbell bench press', es: 'Press de banca con barra' },
  '0026': { en: 'barbell bench squat', es: 'Sentadilla al banco con barra' },
  '0027': { en: 'barbell bent over row', es: 'Remo con barra' },
  '0030': { en: 'barbell close-grip bench press', es: 'Press de banca agarre cerrado' },
  '0031': { en: 'barbell curl', es: 'Curl de bíceps con barra' },
  '0032': { en: 'barbell deadlift', es: 'Peso muerto con barra' },
  '0033': { en: 'barbell decline bench press', es: 'Press de banca declinado con barra' },
  '0041': { en: 'barbell front raise', es: 'Elevaciones frontales con barra' },
  '0042': { en: 'barbell front squat', es: 'Sentadilla frontal con barra' },
  '0043': { en: 'barbell full squat', es: 'Sentadilla con barra' },
  '0044': { en: 'barbell good morning', es: 'Buenos días con barra' },
  '0046': { en: 'barbell hack squat', es: 'Sentadilla hack con barra' },
  '0047': { en: 'barbell incline bench press', es: 'Press de banca inclinado con barra' },
  '0052': { en: 'barbell jm bench press', es: 'Press JM con barra' },
  '0054': { en: 'barbell lunge', es: 'Zancadas con barra' },
  '0060': { en: 'barbell lying triceps extension skull crusher', es: 'Press francés con barra' },
  '0061': { en: 'barbell lying triceps extension', es: 'Extensión de tríceps tumbado con barra' },
  '0070': { en: 'barbell preacher curl', es: 'Curl predicador con barra' },
  '0073': { en: 'barbell pullover', es: 'Pullover con barra' },
  '0074': { en: 'barbell rack pull', es: 'Peso muerto parcial desde rack' },
  '0078': { en: 'barbell rear lunge', es: 'Zancada atrás con barra' },
  '0080': { en: 'barbell reverse curl', es: 'Curl invertido con barra' },
  '0082': { en: 'barbell reverse wrist curl', es: 'Curl de muñeca invertido con barra' },
  '0085': { en: 'barbell romanian deadlift', es: 'Peso muerto rumano con barra' },
  '0086': { en: 'barbell seated behind head military press', es: 'Press tras nuca sentado con barra' },
  '0088': { en: 'barbell seated calf raise', es: 'Elevación de talones sentado con barra' },
  '0090': { en: 'barbell seated good morning', es: 'Buenos días sentado con barra' },
  '0091': { en: 'barbell seated overhead press', es: 'Press militar con barra' },
  '0095': { en: 'barbell shrug', es: 'Encogimientos de hombros con barra' },
  '0099': { en: 'barbell single leg split squat', es: 'Sentadilla búlgara con barra' },
  '0114': { en: 'barbell step-up', es: 'Subida al cajón con barra' },
  '0116': { en: 'barbell straight leg deadlift', es: 'Peso muerto con piernas rectas con barra' },
  '0117': { en: 'barbell sumo deadlift', es: 'Peso muerto sumo' },
  '0118': { en: 'barbell reverse grip bent over row', es: 'Remo con barra agarre supino' },
  '0120': { en: 'barbell upright row', es: 'Remo al mentón con barra' },
  '0122': { en: 'barbell wide bench press', es: 'Press de banca con barra agarre abierto' },
  '0124': { en: 'barbell wide squat', es: 'Sentadilla con barra con piernas abiertas' },
  '0126': { en: 'barbell wrist curl', es: 'Curl de muñeca con barra' },
  '0127': { en: 'barbell zercher squat', es: 'Sentadilla Zercher con barra' },
  '0128': { en: 'battling ropes', es: 'Cuerdas de batalla' },
  '0151': { en: 'cable bench press', es: 'Press de banca en polea' },
  '0154': { en: 'cable cross-over revers fly', es: 'Aperturas invertidas en polea cruzada' },
  '0155': { en: 'cable cross-over variation', es: 'Cruce de poleas' },
  '0157': { en: 'cable deadlift', es: 'Peso muerto en polea' },
  '0162': { en: 'cable front raise', es: 'Elevaciones frontales en polea' },
  '0165': { en: 'cable hammer curl (with rope)', es: 'Curl martillo en polea con cuerda' },
  '0168': { en: 'cable hip adduction', es: 'Aducción de cadera en polea' },
  '0171': { en: 'cable incline fly', es: 'Aperturas en polea en banco inclinado' },
  '0175': { en: 'cable kneeling crunch', es: 'Crunch en polea arrodillado' },
  '0178': { en: 'cable lateral raise', es: 'Elevaciones laterales en polea' },
  '0179': { en: 'cable low fly', es: 'Cruce de poleas de abajo hacia arriba' },
  '0180': { en: 'cable low seated row', es: 'Remo bajo sentado en polea' },
  '0188': { en: 'cable middle fly', es: 'Cruce de poleas a media altura' },
  '0190': { en: 'cable one arm curl', es: 'Curl de bíceps a una mano en polea' },
  '0192': { en: 'cable one arm lateral raise', es: 'Elevación lateral a una mano en polea' },
  '0194': { en: 'cable overhead triceps extension (rope attachment)', es: 'Extensión de tríceps por encima de la cabeza en polea con cuerda' },
  '0195': { en: 'cable preacher curl', es: 'Curl predicador en polea' },
  '0198': { en: 'cable pulldown', es: 'Jalón al pecho' },
  '0200': { en: 'cable pushdown (with rope attachment)', es: 'Extensión de tríceps en polea con cuerda' },
  '0201': { en: 'cable pushdown', es: 'Extensión de tríceps en polea' },
  '0207': { en: 'cable reverse-grip pushdown', es: 'Extensión de tríceps en polea agarre supino' },
  '0215': { en: 'cable seated rear lateral raise', es: 'Pájaros sentado en polea' },
  '0218': { en: 'cable seated wide-grip row', es: 'Remo sentado en polea agarre abierto' },
  '0219': { en: 'cable shoulder press', es: 'Press de hombros en polea' },
  '0220': { en: 'cable shrug', es: 'Encogimientos de hombros en polea' },
  '0222': { en: 'cable side bend', es: 'Flexión lateral de tronco en polea' },
  '0226': { en: 'cable standing crunch', es: 'Crunch de pie en polea' },
  '0227': { en: 'cable standing fly', es: 'Aperturas en polea de pie' },
  '0228': { en: 'cable standing hip extension', es: 'Patada de glúteo en polea' },
  '0233': { en: 'cable standing rear delt row (with rope)', es: 'Face pull con cuerda' },
  '0235': { en: 'cable standing shoulder external rotation', es: 'Rotación externa de hombro en polea' },
  '0238': { en: 'cable straight arm pulldown', es: 'Jalón con brazos rectos en polea' },
  '0241': { en: 'cable triceps pushdown (v-bar)', es: 'Extensión de tríceps en polea con barra en V' },
  '0243': { en: 'cable twist', es: 'Rotación de tronco en polea' },
  '0245': { en: 'cable underhand pulldown', es: 'Jalón al pecho con agarre supino' },
  '0246': { en: 'cable upright row', es: 'Remo al mentón en polea' },
  '0251': { en: 'chest dip', es: 'Fondos en paralelas' },
  '0259': { en: 'close-grip push-up', es: 'Flexiones de brazos con agarre cerrado' },
  '0262': { en: 'cross body crunch', es: 'Crunch cruzado' },
  '0274': { en: 'crunch floor', es: 'Crunch abdominal' },
  '0276': { en: 'dead bug', es: 'Bicho muerto (dead bug)' },
  '0277': { en: 'decline crunch', es: 'Crunch en banco declinado' },
  '0279': { en: 'decline push-up', es: 'Flexiones de brazos declinadas' },
  '0282': { en: 'decline sit-up', es: 'Abdominales completos en banco declinado' },
  '0283': { en: 'diamond push-up', es: 'Flexiones diamante' },
  '0284': { en: 'donkey calf raise', es: 'Elevación de talones tipo burro' },
  '0285': { en: 'dumbbell alternate biceps curl', es: 'Curl de bíceps alterno con mancuernas' },
  '0289': { en: 'dumbbell bench press', es: 'Press de banca con mancuernas' },
  '0292': { en: 'dumbbell one arm bent-over row', es: 'Remo con mancuerna a una mano' },
  '0293': { en: 'dumbbell bent over row', es: 'Remo inclinado con mancuernas' },
  '0294': { en: 'dumbbell biceps curl', es: 'Curl de bíceps con mancuernas' },
  '0297': { en: 'dumbbell concentration curl', es: 'Curl concentrado con mancuerna' },
  '0298': { en: 'dumbbell cross body hammer curl', es: 'Curl martillo cruzado con mancuerna' },
  '0300': { en: 'dumbbell deadlift', es: 'Peso muerto con mancuernas' },
  '0301': { en: 'dumbbell decline bench press', es: 'Press de banca declinado con mancuernas' },
  '0302': { en: 'dumbbell decline fly', es: 'Aperturas en banco declinado con mancuernas' },
  '0303': { en: 'dumbbell decline hammer press', es: 'Press declinado con mancuernas agarre martillo' },
  '0308': { en: 'dumbbell fly', es: 'Aperturas con mancuernas' },
  '0310': { en: 'dumbbell front raise', es: 'Elevaciones frontales con mancuernas' },
  '0313': { en: 'dumbbell hammer curl', es: 'Curl martillo con mancuernas' },
  '0314': { en: 'dumbbell incline bench press', es: 'Press de banca inclinado con mancuernas' },
  '0318': { en: 'dumbbell incline curl', es: 'Curl de bíceps en banco inclinado con mancuernas' },
  '0319': { en: 'dumbbell incline fly', es: 'Aperturas en banco inclinado con mancuernas' },
  '0321': { en: 'dumbbell incline hammer press', es: 'Press inclinado con mancuernas agarre martillo' },
  '0326': { en: 'dumbbell incline rear lateral raise', es: 'Pájaros con mancuernas en banco inclinado' },
  '0327': { en: 'dumbbell incline row', es: 'Remo con mancuernas en banco inclinado' },
  '0333': { en: 'dumbbell kickback', es: 'Patada de tríceps con mancuerna' },
  '0334': { en: 'dumbbell lateral raise', es: 'Elevaciones laterales con mancuernas' },
  '0336': { en: 'dumbbell lunge', es: 'Zancadas con mancuernas' },
  '0339': { en: 'dumbbell lying femoral', es: 'Curl femoral tumbado con mancuerna' },
  '0351': { en: 'dumbbell lying triceps extension', es: 'Extensión de tríceps tumbado con mancuernas' },
  '0352': { en: 'dumbbell neutral grip bench press', es: 'Press de banca con mancuernas agarre neutro' },
  '0355': { en: 'dumbbell one arm lateral raise', es: 'Elevación lateral a una mano con mancuerna' },
  '0361': { en: 'dumbbell one arm shoulder press', es: 'Press de hombro con mancuerna a una mano' },
  '0372': { en: 'dumbbell preacher curl', es: 'Curl predicador con mancuerna' },
  '0375': { en: 'dumbbell pullover', es: 'Pullover con mancuerna' },
  '0380': { en: 'dumbbell rear lateral raise', es: 'Pájaros con mancuernas' },
  '0381': { en: 'dumbbell rear lunge', es: 'Zancada atrás con mancuernas' },
  '0383': { en: 'dumbbell reverse fly', es: 'Aperturas invertidas con mancuernas' },
  '0396': { en: 'dumbbell seated lateral raise', es: 'Elevaciones laterales sentado con mancuernas' },
  '0404': { en: 'dumbbell seated shoulder press (parallel grip)', es: 'Press de hombros con mancuernas sentado agarre neutro' },
  '0405': { en: 'dumbbell seated shoulder press', es: 'Press de hombros con mancuernas sentado' },
  '0406': { en: 'dumbbell shrug', es: 'Encogimientos de hombros con mancuernas' },
  '0407': { en: 'dumbbell side bend', es: 'Flexión lateral de tronco con mancuerna' },
  '0409': { en: 'dumbbell single leg calf raise', es: 'Elevación de talón a una pierna con mancuerna' },
  '0410': { en: 'dumbbell single leg split squat', es: 'Sentadilla búlgara con mancuernas' },
  '0413': { en: 'dumbbell squat', es: 'Sentadilla con mancuernas' },
  '0417': { en: 'dumbbell standing calf raise', es: 'Elevación de talones de pie con mancuernas' },
  '0426': { en: 'dumbbell standing overhead press', es: 'Press de hombros con mancuernas de pie' },
  '0430': { en: 'dumbbell standing triceps extension', es: 'Extensión de tríceps por encima de la cabeza con mancuerna' },
  '0431': { en: 'dumbbell step-up', es: 'Subida al cajón con mancuernas' },
  '0432': { en: 'dumbbell stiff leg deadlift', es: 'Peso muerto con piernas rígidas con mancuernas' },
  '0436': { en: 'dumbbell tate press', es: 'Press Tate con mancuernas' },
  '0437': { en: 'dumbbell upright row', es: 'Remo al mentón con mancuernas' },
  '0439': { en: 'dumbbell zottman curl', es: 'Curl Zottman con mancuernas' },
  '0446': { en: 'ez barbell close-grip curl', es: 'Curl de bíceps con barra Z agarre cerrado' },
  '0447': { en: 'ez barbell curl', es: 'Curl de bíceps con barra Z' },
  '0453': { en: 'ez barbell seated triceps extension', es: 'Extensión de tríceps sentado con barra Z' },
  '0454': { en: 'ez barbell spider curl', es: 'Curl araña con barra Z' },
  '0459': { en: 'flutter kicks', es: 'Patadas de tijera alternas' },
  '0464': { en: 'front plank with twist', es: 'Plancha frontal con giro' },
  '0472': { en: 'hanging leg raise', es: 'Elevación de piernas colgado' },
  '0488': { en: 'hyperextension (on bench)', es: 'Hiperextensiones en banco' },
  '0489': { en: 'hyperextension', es: 'Hiperextensiones' },
  '0493': { en: 'incline push-up', es: 'Flexiones de brazos inclinadas' },
  '0496': { en: 'inverse leg curl (bench support)', es: 'Curl nórdico con apoyo en banco' },
  '0499': { en: 'inverted row', es: 'Remo invertido' },
  '0507': { en: 'jackknife sit-up', es: 'Navaja abdominal' },
  '0514': { en: 'jump squat', es: 'Sentadilla con salto' },
  '0533': { en: 'kettlebell front squat', es: 'Sentadilla frontal con kettlebell' },
  '0534': { en: 'kettlebell goblet squat', es: 'Sentadilla goblet con kettlebell' },
  '0535': { en: 'kettlebell hang clean', es: 'Cargada colgante con kettlebell' },
  '0541': { en: 'kettlebell one arm row', es: 'Remo a una mano con kettlebell' },
  '0542': { en: 'kettlebell one arm snatch', es: 'Arrancada a una mano con kettlebell' },
  '0549': { en: 'kettlebell swing', es: 'Swing con kettlebell' },
  '0551': { en: 'kettlebell turkish get up (squat style)', es: 'Levantamiento turco con kettlebell' },
  '0553': { en: 'kettlebell two arm military press', es: 'Press militar con kettlebells' },
  '0554': { en: 'kettlebell windmill', es: 'Molino con kettlebell' },
  '0572': { en: 'lever assisted chin-up', es: 'Dominadas supinas asistidas en máquina' },
  '0573': { en: 'lever back extension', es: 'Extensión lumbar en máquina' },
  '0575': { en: 'lever bicep curl', es: 'Curl de bíceps en máquina' },
  '0576': { en: 'lever chest press', es: 'Press de pecho en máquina' },
  '0578': { en: 'lever deadlift', es: 'Peso muerto en máquina' },
  '0579': { en: 'lever front pulldown', es: 'Jalón al pecho en máquina' },
  '0581': { en: 'lever high row', es: 'Remo alto en máquina' },
  '0584': { en: 'lever lateral raise', es: 'Elevaciones laterales en máquina' },
  '0585': { en: 'lever leg extension', es: 'Extensión de cuádriceps en máquina' },
  '0586': { en: 'lever lying leg curl', es: 'Curl femoral tumbado en máquina' },
  '0587': { en: 'lever military press', es: 'Press militar en máquina' },
  '0588': { en: 'lever narrow grip seated row', es: 'Remo sentado agarre estrecho en máquina' },
  '0591': { en: 'lever overhand triceps dip', es: 'Fondos de tríceps en máquina' },
  '0592': { en: 'lever preacher curl', es: 'Curl predicador en máquina' },
  '0593': { en: 'lever reverse hyperextension', es: 'Hiperextensión inversa en máquina' },
  '0594': { en: 'lever seated calf raise', es: 'Elevación de talones sentado en máquina' },
  '0595': { en: 'lever seated crunch (chest pad)', es: 'Crunch en máquina' },
  '0596': { en: 'lever seated fly', es: 'Aperturas en máquina' },
  '0597': { en: 'lever seated hip abduction', es: 'Abducción de cadera en máquina' },
  '0598': { en: 'lever seated hip adduction', es: 'Aducción de cadera en máquina' },
  '0599': { en: 'lever seated leg curl', es: 'Curl femoral sentado en máquina' },
  '0602': { en: 'lever seated reverse fly', es: 'Aperturas invertidas en máquina' },
  '0603': { en: 'lever shoulder press', es: 'Press de hombros en máquina' },
  '0604': { en: 'lever shrug', es: 'Encogimientos de hombros en máquina' },
  '0605': { en: 'lever standing calf raise', es: 'Elevación de talones de pie en máquina' },
  '0606': { en: 'lever t bar row', es: 'Remo en T en máquina' },
  '0607': { en: 'lever triceps extension', es: 'Extensión de tríceps en máquina' },
  '0620': { en: 'lying leg raise flat bench', es: 'Elevación de piernas tumbado en banco' },
  '0630': { en: 'mountain climber', es: 'Escaladores (mountain climbers)' },
  '0635': { en: 'oblique crunches floor', es: 'Crunch oblicuo en el suelo' },
  '0648': { en: 'power clean', es: 'Cargada de potencia con barra' },
  '0651': { en: 'pull up (neutral grip)', es: 'Dominadas con agarre neutro' },
  '0652': { en: 'pull-up', es: 'Dominadas' },
  '0659': { en: 'push-up (wall)', es: 'Flexiones de brazos en la pared' },
  '0662': { en: 'push-up', es: 'Flexiones de brazos' },
  '0684': { en: 'run (equipment)', es: 'Carrera en cinta' },
  '0685': { en: 'run', es: 'Trote' },
  '0687': { en: 'russian twist', es: 'Giros rusos' },
  '0688': { en: 'scapular pull-up', es: 'Dominadas escapulares' },
  '0705': { en: 'side bridge v. 2', es: 'Plancha lateral' },
  '0710': { en: 'side hip abduction', es: 'Abducción de cadera tumbado de lado' },
  '0735': { en: 'sit-up v. 2', es: 'Abdominales completos' },
  '0739': { en: 'sled 45в° leg press', es: 'Prensa de piernas 45°' },
  '0743': { en: 'sled hack squat', es: 'Sentadilla hack' },
  '0748': { en: 'smith bench press', es: 'Press de banca en máquina Smith' },
  '0751': { en: 'smith close-grip bench press', es: 'Press de banca agarre cerrado en máquina Smith' },
  '0752': { en: 'smith deadlift', es: 'Peso muerto en máquina Smith' },
  '0753': { en: 'smith decline bench press', es: 'Press de banca declinado en máquina Smith' },
  '0755': { en: 'smith hack squat', es: 'Sentadilla hack en máquina Smith' },
  '0757': { en: 'smith incline bench press', es: 'Press de banca inclinado en máquina Smith' },
  '0760': { en: 'smith leg press', es: 'Prensa de piernas en máquina Smith' },
  '0765': { en: 'smith seated shoulder press', es: 'Press de hombros sentado en máquina Smith' },
  '0767': { en: 'smith shrug', es: 'Encogimientos de hombros en máquina Smith' },
  '0770': { en: 'smith squat', es: 'Sentadilla en máquina Smith' },
  '0773': { en: 'smith standing leg calf raise', es: 'Elevación de talones de pie en máquina Smith' },
  '0774': { en: 'smith standing military press', es: 'Press militar de pie en máquina Smith' },
  '0775': { en: 'smith upright row', es: 'Remo al mentón en máquina Smith' },
  '0798': { en: 'stationary bike walk', es: 'Bicicleta estática' },
  '0811': { en: 'trap bar deadlift', es: 'Peso muerto con barra hexagonal' },
  '0812': { en: 'triceps dip (bench leg)', es: 'Fondos de tríceps en banco' },
  '0814': { en: 'triceps dip', es: 'Fondos de tríceps en paralelas' },
  '0818': { en: 'twin handle parallel grip lat pulldown', es: 'Jalón al pecho con agarre estrecho' },
  '0826': { en: 'vertical leg raise (on parallel bars)', es: 'Elevación de piernas en paralelas' },
  '0832': { en: 'weighted crunch', es: 'Crunch abdominal con peso' },
  '0834': { en: 'weighted front raise', es: 'Elevación frontal con disco' },
  '0841': { en: 'weighted pull-up', es: 'Dominadas con lastre' },
  '0846': { en: 'weighted russian twist', es: 'Giros rusos con peso' },
  '0857': { en: 'wheel rollerout', es: 'Rueda abdominal' },
  '0860': { en: 'cable kickback', es: 'Patada de tríceps en polea' },
  '0861': { en: 'cable seated row', es: 'Remo sentado en polea' },
  '0865': { en: 'lying leg-hip raise', es: 'Elevación de piernas y cadera tumbado' },
  '0868': { en: 'cable curl', es: 'Curl de bíceps en polea' },
  '0872': { en: 'reverse crunch', es: 'Crunch invertido' },
  '0968': { en: 'band alternating biceps curl', es: 'Curl de bíceps alterno con banda' },
  '0970': { en: 'band assisted pull-up', es: 'Dominadas asistidas con banda' },
  '0974': { en: 'band close-grip pulldown', es: 'Jalón al pecho agarre cerrado con banda' },
  '0975': { en: 'band close-grip push-up', es: 'Flexiones de brazos agarre cerrado con banda' },
  '0978': { en: 'band front raise', es: 'Elevaciones frontales con banda' },
  '0979': { en: 'band horizontal pallof press', es: 'Press Pallof con banda' },
  '0988': { en: 'band one arm standing low row', es: 'Remo bajo de pie con banda a una mano' },
  '0991': { en: 'band pull through', es: 'Extensión de cadera con banda entre las piernas' },
  '0993': { en: 'band reverse fly', es: 'Aperturas invertidas con banda' },
  '0997': { en: 'band shoulder press', es: 'Press de hombros con banda' },
  '0998': { en: 'band side triceps extension', es: 'Extensión de tríceps lateral con banda' },
  '0999': { en: 'band single leg calf raise', es: 'Elevación de talón a una pierna con banda' },
  '1001': { en: 'band single leg split squat', es: 'Sentadilla búlgara con banda' },
  '1003': { en: 'band squat row', es: 'Sentadilla con remo con banda' },
  '1004': { en: 'band squat', es: 'Sentadilla con banda' },
  '1008': { en: 'band step-up', es: 'Subida al cajón con banda' },
  '1009': { en: 'band stiff leg deadlift', es: 'Peso muerto con piernas rígidas con banda' },
  '1013': { en: 'band underhand pulldown', es: 'Jalón supino con banda' },
  '1018': { en: 'band shrug', es: 'Encogimientos de hombros con banda' },
  '1022': { en: 'band standing rear delt row', es: 'Face pull con banda' },
  '1160': { en: 'burpee', es: 'Burpees' },
  '1254': { en: 'band bench press', es: 'Press de banca con banda' },
  '1270': { en: 'cable upper chest crossovers', es: 'Cruce de poleas para pecho superior' },
  '1299': { en: 'lever incline chest press', es: 'Press de pecho inclinado en máquina' },
  '1300': { en: 'lever decline chest press', es: 'Press de pecho declinado en máquina' },
  '1306': { en: 'plyo push up', es: 'Flexiones pliométricas' },
  '1311': { en: 'wide hand push up', es: 'Flexiones de brazos con agarre abierto' },
  '1323': { en: 'cable rope seated row', es: 'Remo sentado en polea con cuerda' },
  '1326': { en: 'chin-up', es: 'Dominadas supinas' },
  '1327': { en: 'close grip chin-up', es: 'Dominadas supinas con agarre cerrado' },
  '1350': { en: 'lever seated row', es: 'Remo sentado en máquina' },
  '1354': { en: 'medicine ball overhead slam', es: 'Lanzamiento de balón medicinal al suelo' },
  '1359': { en: 'smith bent over row', es: 'Remo con barra en máquina Smith' },
  '1369': { en: 'band two legs calf raise - (band under both legs) v. 2', es: 'Elevación de talones con banda' },
  '1372': { en: 'barbell standing calf raise', es: 'Elevación de talones de pie con barra' },
  '1373': { en: 'bodyweight standing calf raise', es: 'Elevación de talones de pie con peso corporal' },
  '1375': { en: 'cable standing calf raise', es: 'Elevación de talones de pie en polea' },
  '1379': { en: 'dumbbell seated calf raise', es: 'Elevación de talones sentado con mancuernas' },
  '1391': { en: 'sled calf press on leg press', es: 'Elevación de talones en prensa' },
  '1408': { en: 'band hip lift', es: 'Puente de glúteo con banda' },
  '1409': { en: 'barbell glute bridge', es: 'Puente de glúteo con barra (hip thrust)' },
  '1410': { en: 'barbell lateral lunge', es: 'Zancada lateral con barra' },
  '1425': { en: 'sled 45 degrees one leg press', es: 'Prensa de piernas 45° a una pierna' },
  '1429': { en: 'wide grip pull-up', es: 'Dominadas con agarre abierto' },
  '1433': { en: 'smith front squat (clean grip)', es: 'Sentadilla frontal en máquina Smith' },
  '1435': { en: 'barbell low bar squat', es: 'Sentadilla con barra baja' },
  '1436': { en: 'barbell high bar squat', es: 'Sentadilla con barra alta' },
  '1452': { en: 'lever seated crunch', es: 'Crunch sentado en máquina' },
  '1456': { en: 'barbell standing close grip military press', es: 'Press militar de pie con barra agarre cerrado' },
  '1457': { en: 'barbell standing wide military press', es: 'Press militar de pie con barra agarre abierto' },
  '1459': { en: 'dumbbell romanian deadlift', es: 'Peso muerto rumano con mancuernas' },
  '1460': { en: 'walking lunge', es: 'Zancadas caminando' },
  '1627': { en: 'ez barbell close grip preacher curl', es: 'Curl predicador con barra Z' },
  '1631': { en: 'cable concentration curl', es: 'Curl concentrado en polea' },
  '1677': { en: 'dumbbell seated bicep curl', es: 'Curl de bíceps sentado con mancuernas' },
  '1678': { en: 'dumbbell seated hammer curl', es: 'Curl martillo sentado con mancuernas' },
  '1700': { en: 'dumbbell push press', es: 'Press de empuje con mancuernas' },
  '1722': { en: 'cable high pulley overhead tricep extension', es: 'Extensión de tríceps por encima de la cabeza en polea' },
  '1723': { en: 'cable one arm tricep pushdown', es: 'Extensión de tríceps en polea a una mano' },
  '1749': { en: 'ez bar standing french press', es: 'Press francés de pie con barra Z' },
  '1755': { en: 'weighted tricep dips', es: 'Fondos de tríceps con lastre' },
  '1756': { en: 'barbell single leg deadlift', es: 'Peso muerto a una pierna con barra' },
  '1757': { en: 'dumbbell single leg deadlift', es: 'Peso muerto a una pierna con mancuerna' },
  '1759': { en: 'single leg squat (pistol) male', es: 'Sentadilla a una pierna' },
  '1760': { en: 'dumbbell goblet squat', es: 'Sentadilla goblet con mancuerna' },
  '1775': { en: 'side plank hip adduction', es: 'Plancha Copenhague (aducción en plancha lateral)' },
  '2133': { en: 'farmers walk', es: 'Paseo del granjero' },
  '2135': { en: 'weighted front plank', es: 'Plancha frontal' },
  '2137': { en: 'dumbbell arnold press', es: 'Press Arnold' },
  '2138': { en: 'stationary bike run v. 3', es: 'Bicicleta estática a ritmo intenso' },
  '2139': { en: 'hands bike', es: 'Ergómetro de brazos' },
  '2141': { en: 'walk elliptical cross trainer', es: 'Elíptica' },
  '2142': { en: 'ski ergometer', es: 'Ergómetro de esquí (SkiErg)' },
  '2144': { en: 'cable seated chest press', es: 'Press de pecho sentado en polea' },
  '2188': { en: 'dumbbell seated triceps extension', es: 'Extensión de tríceps sentado con mancuerna' },
  '2286': { en: 'lever hip extension v. 2', es: 'Extensión de cadera en máquina' },
  '2311': { en: 'walking on stepmill', es: 'Escaladora (stepmill)' },
  '2368': { en: 'split squats', es: 'Sentadilla dividida (split squat)' },
  '2432': { en: 'ez-bar close-grip bench press', es: 'Press de banca agarre cerrado con barra Z' },
  '2611': { en: 'lever horizontal one leg press', es: 'Prensa horizontal a una pierna en máquina' },
  '2612': { en: 'jump rope', es: 'Saltar la cuerda' },
  '2616': { en: 'cable lateral pulldown with v-bar', es: 'Jalón al pecho con triángulo' },
  '2963': { en: 'captains chair straight leg raise', es: 'Elevación de piernas rectas en silla romana' },
  '3006': { en: 'resistance band seated hip abduction', es: 'Abducción de cadera sentado con banda' },
  '3007': { en: 'resistance band leg extension', es: 'Extensión de piernas con banda' },
  '3013': { en: 'low glute bridge on floor', es: 'Puente de glúteo en el suelo' },
  '3017': { en: 'barbell pendlay row', es: 'Remo Pendlay con barra' },
  '3122': { en: 'resistance band seated shoulder press', es: 'Press de hombros sentado con banda' },
  '3123': { en: 'resistance band seated biceps curl', es: 'Curl de bíceps sentado con banda' },
  '3124': { en: 'resistance band seated chest press', es: 'Press de pecho sentado con banda' },
  '3132': { en: 'potty squat with support', es: 'Sentadilla profunda con apoyo' },
  '3142': { en: 'smith sumo squat', es: 'Sentadilla sumo en máquina Smith' },
  '3144': { en: 'resistance band seated straight back row', es: 'Remo sentado con banda' },
  '3166': { en: 'bodyweight standing row', es: 'Remo de pie con peso corporal' },
  '3211': { en: 'kneeling push-up (male)', es: 'Flexiones de brazos con rodillas apoyadas' },
  '3224': { en: 'jack jump (male)', es: 'Saltos de tijera' },
  '3305': { en: 'barbell thruster', es: 'Sentadilla con press con barra' },
  '3360': { en: 'bear crawl', es: 'Caminata de oso' },
  '3361': { en: 'skater hops', es: 'Saltos de patinador' },
  '3470': { en: 'forward lunge (male)', es: 'Zancada al frente' },
  '3523': { en: 'glute bridge two legs on bench (male)', es: 'Puente de glúteo con pies en banco' },
  '3533': { en: 'quads', es: 'Sentadilla con peso corporal' },
  '3541': { en: 'dumbbell incline y-raise', es: 'Elevación en Y en banco inclinado con mancuernas' },
  '3561': { en: 'glute bridge march', es: 'Puente de glúteo con marcha' },
  '3645': { en: 'single leg bridge with outstretched leg', es: 'Puente de glúteo a una pierna' },
  '3666': { en: 'walking on incline treadmill', es: 'Caminata en cinta inclinada' },
  '3699': { en: 'shoulder tap', es: 'Plancha con toque de hombro' },
  '3769': { en: 'curtsey squat', es: 'Sentadilla cruzada (reverencia)' },
};
